### ISSUE TITLE
Not working in Linux

### ISSUE THREAD

**Issue by gowtham758550** [Raagul26/Password-Manager-and-Generator--GUI#1]
![signal-2020-07-18-160852](https://user-images.githubusercontent.com/63159252/87850899-51aada80-c911-11ea-9e76-b0a455b12a5d.png)

It shows error when try to run this code.

**Comment by Anish-M-code** [comment]
i tried commenting the line containing  window.iconbitmap(icon) and code works. i issued a pull request to fix this issue, hope it works .

**Comment by Raagul26** [comment]
Now it is compatible for linux.
