### ISSUE TITLE
Request to update code to latest Password generater and manager version 2.0 release.

### ISSUE THREAD

**Issue by Anish-M-code** [Raagul26/Password-Manager-and-Generator--GUI#3]
The latest Password generator and manager project available at https://github.com/gowtham758550/password-generator-and-manager has released version 2.0 release which makes password recovery attacks much harder and defend against password recovery tools such as https://github.com/gowtham758550/password-generator-and-manager/blob/master/Password%20Recovery/nopass.py . Please update code accordingly to patch these issues. Thanks in Advance...

**Comment by Raagul26** [comment]
Updated to latest version.
